subgraphs:
  user:
    routing_url: http://localhost:4300/
    schema:
      subgraph_url: http://localhost:4300/
  book:
    routing_url: http://localhost:4200/
    schema:
      subgraph_url: http://localhost:4200/